### ISSUE TITLE
[Feature]: Hi，add bilibili videos list is useful

### ISSUE THREAD

**Issue by allinu** [gautamkrishnar/blog-post-workflow#15]
**Is your feature request related to a problem? Please describe.**
yes, i don't know how to add bilibili website videos in this workflow

**Describe the solution you'd like**
i need add bilibili web suppert in this workflow

**Describe alternatives you've considered**
none

**Additional context**

**Comment by gautamkrishnar** [comment]
@allinu Sorry, I don't think that this is possible since billbill doesn't support provide user-generated content as XML format. I tried googling but couldn't find anything other than this: https://ir.bilibili.com/rss-feeds, which is not related to anything you require.

I am also not good with Chinese language. If you find anything related to this and think that there's an XML source, please feel free to reopen.
