### ISSUE TITLE
[Bug]: Hugo links seem to not work?

### ISSUE THREAD

**Issue by DataStrategist** [gautamkrishnar/blog-post-workflow#17]
**Describe the bug**
I'm trying to use this workflow on https://www.amitkohli.com/ this blog, which runs Hugo and is deployed through Netlify.

The RSS feed for this is: https://www.amitkohli.com/index.xml

**To Reproduce**
 - Change your feed to https://www.amitkohli.com/index.xml and you will see this error talking about a parse failure.

![image](https://user-images.githubusercontent.com/8094091/89780657-cb497900-db09-11ea-86c7-09a627b6ea3b.png)

You can see my failed runs here: https://github.com/DataStrategist/DataStrategist/actions
**Expected behavior**
I would like to see the links to my latest blogposts in my front-page :)

Thanks for an excellent bit of software!

**Comment by gautamkrishnar** [comment]
Hi @DataStrategist Looks like its the problem with the XML data you are giving, the title tag is empty for your posts:
<img width="1094" alt="Screenshot 2020-08-10 at 10 25 15 PM" src="https://user-images.githubusercontent.com/8397274/89808885-6ec17a80-db58-11ea-881d-c248e75cd1c1.png">

Please check your hugo cms configuration since this is not the correct format of the XML feeds.
